In [1]:
import numpy as np
a4=np.random.randint(25,size=(2,3,4,5))
a4

array([[[[13,  2,  9, 24,  7],
         [ 0, 13, 20,  2, 22],
         [ 3, 13,  0, 15, 16],
         [11, 15, 20,  0, 21]],

        [[ 2, 21, 11, 16,  3],
         [12, 14, 23, 16,  0],
         [24, 22, 17, 23, 18],
         [ 2, 21,  8, 13,  2]],

        [[12, 13, 16, 22,  1],
         [ 0, 19, 18, 22, 21],
         [ 5,  3,  2, 18,  2],
         [16,  5,  4, 23, 10]]],


       [[[15, 12, 10, 14,  5],
         [17, 24, 15, 24, 12],
         [16, 20, 21, 17, 19],
         [14, 13, 15, 12, 17]],

        [[ 4, 16, 23, 10, 23],
         [19, 14, 17,  4,  7],
         [22,  0,  8, 14, 22],
         [ 2, 24, 11, 10, 23]],

        [[19,  0,  4, 20, 11],
         [ 8, 22, 19, 20,  8],
         [17,  8, 20, 20, 10],
         [ 9,  2,  1,  2,  3]]]])

## Manipulating and comparing arrays

### Arithmetic 

#### basic

In [4]:
import numpy as np
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [6]:
a1+ones

array([2., 3., 4.])

In [7]:
a1 -ones

array([0., 1., 2.])

In [8]:
a1*ones

array([1., 2., 3.])

In [9]:
a1%ones

array([0., 0., 0.])

In [10]:
a1/ones

array([1., 2., 3.])

In [11]:
a2 = np.array([[1,2,3.5],
               [5,6,7]])
a2

array([[1. , 2. , 3.5],
       [5. , 6. , 7. ]])

In [12]:
a1 *a2

array([[ 1. ,  4. , 10.5],
       [ 5. , 12. , 21. ]])

In [15]:
a34= np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]],
             )
a34

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [18]:
# How can you reshape a2 to be compatible with a34
#Searcth :'how to reshape numpy arrays'
a2 * a34

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [20]:
a2 / a1

array([[1.        , 1.        , 1.16666667],
       [5.        , 3.        , 2.33333333]])

In [21]:
# Floor division removes the decimals (rounds down) 
a2//a1

array([[1., 1., 1.],
       [5., 3., 2.]])

In [22]:
a34 ** 2

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[100, 121, 144],
        [169, 196, 225],
        [256, 289, 324]]])

In [23]:
a2 ** 2

array([[ 1.  ,  4.  , 12.25],
       [25.  , 36.  , 49.  ]])

In [24]:
np.add(a1,ones)

array([2., 3., 4.])

In [25]:
np.square(a2)

array([[ 1.  ,  4.  , 12.25],
       [25.  , 36.  , 49.  ]])

In [27]:
np.divide(a2,a1)

array([[1.        , 1.        , 1.16666667],
       [5.        , 3.        , 2.33333333]])

In [28]:
np.exp(a34)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]],

       [[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
        [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]]])

In [29]:
np.log(a2)

array([[0.        , 0.69314718, 1.25276297],
       [1.60943791, 1.79175947, 1.94591015]])

### AGGREGATION

#### It's performing the same operation on a number of things

In [32]:
listy_list=[1,2,3,4]
type(listy_list)

list

In [33]:
sum(listy_list)

10

# use pythons methods('sum()') to python data types
#numpy methods ('np.sum()') to numpy arrays

In [36]:
# Creative massive numpy array
massive_array=np.random.random(1000000)
massive_array

array([0.78478168, 0.68098476, 0.74712784, ..., 0.97336857, 0.38763882,
       0.15776407])

In [38]:
massive_array[:100]

array([7.84781682e-01, 6.80984756e-01, 7.47127840e-01, 6.96442560e-01,
       4.08516044e-01, 5.61281452e-01, 6.88874832e-01, 5.55556014e-01,
       5.54641540e-01, 9.80788062e-01, 4.56433752e-01, 9.99663729e-01,
       4.12334146e-02, 7.31406211e-01, 9.26722863e-01, 1.85526647e-01,
       8.42327211e-01, 6.85083030e-01, 9.13394145e-01, 2.75218051e-02,
       5.93617454e-01, 4.62946295e-01, 1.26797770e-01, 5.89888504e-01,
       2.81779846e-01, 1.48987588e-01, 8.50259291e-01, 3.38439188e-01,
       5.87339173e-01, 9.17749050e-01, 4.43295821e-01, 4.81014160e-04,
       8.69730330e-01, 2.83522133e-01, 9.69403393e-01, 7.41285349e-01,
       7.84967964e-02, 2.42735314e-01, 7.68912295e-01, 7.46026560e-01,
       1.79661883e-01, 5.16360666e-01, 6.58155152e-01, 6.29851158e-01,
       3.04453382e-01, 1.37279318e-01, 4.84793867e-01, 2.79146524e-01,
       5.89728076e-01, 4.10798175e-01, 7.45125331e-01, 7.67024716e-01,
       9.64381426e-01, 1.57988246e-01, 9.50629122e-01, 7.02220176e-01,
      

In [39]:
massive_array[:10]

array([0.78478168, 0.68098476, 0.74712784, 0.69644256, 0.40851604,
       0.56128145, 0.68887483, 0.55555601, 0.55464154, 0.98078806])

In [40]:
%timeit sum(massive_array) #python's sum
%timeit np.sum(massive_array) #numpy's sum

188 ms ± 5.63 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.78 ms ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [41]:
np.mean(a2)

4.083333333333333

In [42]:
np.mean(a34)

9.5

In [43]:
np.max(a34)

18

In [45]:
np.min(a2)

1.0

In [46]:
# standard deviation= is measure of how spread out the number is from the mean
np.std(massive_array)

0.28887127459479806

In [47]:
# variance=Measure of the average degree to which each number is different to the mean
#Higher Variance = wider range of numbers
#Lower variance = lower range of numbers
np.var(a34)

26.916666666666668

In [48]:
np.std(a34)

5.188127472091127

In [49]:
# demo of std and var
High_var_array=np.array([100,300,700,1200,3000])
low_var_array=np.array([12,4,6,7,8])

In [50]:
np.var(High_var_array),np.var(low_var_array)

(1082400.0, 7.040000000000001)

In [52]:
np.std(High_var_array),np.std(low_var_array)

(1040.384544291196, 2.65329983228432)

In [3]:
%matplotlib online
import matplotlib.pyplot as plt
plt.hist(High_var_array)
plt.show()

KeyError: 'online'

### Reshaping &transposing

In [5]:
import numpy as np
a2 = np.array([[1,2,3.5],
               [5,6,7]])
a2

array([[1. , 2. , 3.5],
       [5. , 6. , 7. ]])

In [6]:
a2.shape

(2, 3)

In [7]:
a34= np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]],
             )
a34

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a34.shape

(2, 3, 3)

In [11]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.5]],

       [[5. ],
        [6. ],
        [7. ]]])

In [12]:
a2_reshape =a2.reshape(2,3,1)
a2_reshape 

array([[[1. ],
        [2. ],
        [3.5]],

       [[5. ],
        [6. ],
        [7. ]]])

In [14]:
a2_reshape *a34

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 24.5,  28. ,  31.5]],

       [[ 50. ,  55. ,  60. ],
        [ 78. ,  84. ,  90. ],
        [112. , 119. , 126. ]]])

In [16]:
#Transpose = swiches the axis
a2.T

array([[1. , 5. ],
       [2. , 6. ],
       [3.5, 7. ]])

In [18]:
a2.T.shape

(3, 2)

In [19]:
a34.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot product

In [21]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [22]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [23]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [24]:
#Elementwise multiplication(hadarmard multiplication)
mat1 *mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [1]:
#Dot product

np,dot(mat1,mat2)

NameError: name 'np' is not defined

## ASSIGNMENT NUMPY

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
# Create a 2-dimensional NumPy array using np.array()
a2 =np.array([[1,2,3,4],
              [4,5,6,7]])
a2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [6]:
a3 = np.array([[a,b,c,d],
               [e,f,g,h]])

NameError: name 'a' is not defined

In [7]:
a3 = np.array([[10,20,30,40],
               [16,17,18,19]])
a3

array([[10, 20, 30, 40],
       [16, 17, 18, 19]])

In [26]:
# Create a 3-dimensional Numpy array using np.array()
import numpy as np

a4 = np.array([[[1, 2, 3, 4, 5, 6],
               [4, 5, 6, 7, 8, 9],
               [10, 17, 18, 19, 20, 21]],
               [[21, 22, 23, 24, 25, 26],
               [28, 29, 30, 31, 32, 33],
               [34, 35, 36, 37, 38, 39]]],
               )

a4

array([[[ 1,  2,  3,  4,  5,  6],
        [ 4,  5,  6,  7,  8,  9],
        [10, 17, 18, 19, 20, 21]],

       [[21, 22, 23, 24, 25, 26],
        [28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39]]])

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np.shape(a1)

(3,)

In [18]:
np.a1.dtype

AttributeError: module 'numpy' has no attribute 'a1'

In [19]:
a1.dtype

dtype('int32')

In [20]:
a1.size

3

In [22]:
a1.type()

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [23]:
a1.ndim

1

In [25]:
type(a1)

numpy.ndarray

In [27]:
a4.ndim

3

In [28]:
type(a4)

numpy.ndarray

In [29]:
a4.size

36

In [30]:
a4.shape

(2, 3, 6)

In [31]:
# Create an array of shape (10, 2) with only ones
ones =np.array.ones((10, 2),float)

AttributeError: 'builtin_function_or_method' object has no attribute 'ones'

In [33]:
ones = np.ones((10, 2),float)
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
# Create an array of shape (7, 2, 3) of only zeros
zeros =np.zeros((7, 2, 3),int)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [41]:
# Create an array within a range of 0 and 100 with step 3
dorice=np.arange(0,100,3)
dorice


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [43]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_a1=np.random.randint(0,10,size=(1,2))
random_a1

array([[9, 3]])

In [44]:
random_a12=np.random.rand(2,4,5)
random_a12

array([[[0.33586041, 0.65061685, 0.16820989, 0.41060108, 0.171595  ],
        [0.84740227, 0.97100065, 0.44444071, 0.41591803, 0.69673982],
        [0.39754866, 0.94363131, 0.10770719, 0.23905695, 0.14726991],
        [0.5419855 , 0.33912962, 0.1868098 , 0.91609154, 0.02460657]],

       [[0.73766211, 0.4444994 , 0.94985396, 0.40566727, 0.65207573],
        [0.71144935, 0.07123856, 0.01798072, 0.03928103, 0.53832304],
        [0.38426538, 0.33190763, 0.73890744, 0.21910297, 0.02481963],
        [0.27723781, 0.04068677, 0.23573053, 0.99062465, 0.72359389]]])

In [6]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
import numpy as np
np.random.seed(10)
random_45 = np.random.rand(3,5)
random_45

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [8]:
# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
random_array56=np.random.rand(4,6)
random_array56

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

### comparison operators

In [4]:
a1

array([1, 2, 3])

In [8]:
# Create a 3-dimensional Numpy array using np.array()
import numpy as np

a4 = np.array([[[1, 2, 3, 4, 5, 6],
               [4, 5, 6, 7, 8, 9],
               [10, 17, 18, 19, 20, 21]],
               [[21, 22, 23, 24, 25, 26],
               [28, 29, 30, 31, 32, 33],
               [34, 35, 36, 37, 38, 39]]],
               )

a4

array([[[ 1,  2,  3,  4,  5,  6],
        [ 4,  5,  6,  7,  8,  9],
        [10, 17, 18, 19, 20, 21]],

       [[21, 22, 23, 24, 25, 26],
        [28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39]]])

In [22]:
a3 = np.array([[10,20,30],
               [16,17,18]])
a3

array([[10, 20, 30],
       [16, 17, 18]])

In [13]:

a4 > a3

ValueError: operands could not be broadcast together with shapes (2,3,6) (2,4) 

In [20]:
a3_reshape=a3.reshape(2,4,0)
a3_reshape

ValueError: cannot reshape array of size 8 into shape (2,4,0)

In [21]:
a4>a3_reshape

ValueError: operands could not be broadcast together with shapes (2,3,6) (2,4,1) 

In [23]:
a1 > a3

array([[False, False, False],
       [False, False, False]])

In [25]:
bool_array=a1 >= a3
bool_array

array([[False, False, False],
       [False, False, False]])

In [26]:
type(bool_array) ,bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [27]:
a1>5

array([False, False, False])

In [28]:
a1 < 5

array([ True,  True,  True])

In [29]:
a1==5

array([False, False, False])

a1==a3 

In [30]:
a1==a3

array([[False, False, False],
       [False, False, False]])

### sorting arrays

In [32]:
random_array =np.random.randint(10,size=(3,5))
random_array

array([[2, 6, 4, 2, 4],
       [9, 6, 4, 2, 0],
       [0, 6, 0, 7, 6]])

In [33]:
np.sort(random_array)

array([[2, 2, 4, 4, 6],
       [0, 2, 4, 6, 9],
       [0, 0, 6, 6, 7]])

In [34]:
np.argsort(random_array)

array([[0, 3, 2, 4, 1],
       [4, 3, 2, 1, 0],
       [0, 2, 1, 4, 3]], dtype=int64)

In [6]:
a1 = np.array([1,2,3])
a1

NameError: name 'np' is not defined

## Practical Example -Numpy in Action


In [2]:
<img src="pictures/panda.png"/>

SyntaxError: invalid syntax (3597453568.py, line 1)

In [1]:
from ipython import display
display.image("panda.png")

ModuleNotFoundError: No module named 'ipython'

In [5]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("desktop/numpy images/pandas.png")
print(type(panda))

FileNotFoundError: [Errno 2] No such file or directory: 'desktop/numpy images/pandas.png'

### continuation of numpy assingment

In [32]:
import numpy as np 
rand_array=np.random.randint(10,size=(3,5))
np.unique(rand_array)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [17]:
# Find the 0'th index of the latest array you created
rand_array  [:7]

array([[4, 7, 1, 4, 7, 2, 4],
       [7, 4, 5, 7, 1, 5, 2],
       [7, 7, 6, 2, 7, 1, 0]])

In [18]:
# Get the first 2 rows of latest array you created

rand_array  [0:2]

array([[4, 7, 1, 4, 7, 2, 4],
       [7, 4, 5, 7, 1, 5, 2]])

In [26]:
# Get the first 2 values of the first 2 rows of the latest array
rand_array  [2:2]

array([], shape=(0, 7), dtype=int32)

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ones_1 =np.ones((3,5),int)
rand_array,ones_1


(array([[1, 4, 9, 0, 4],
        [3, 6, 4, 8, 4],
        [4, 2, 8, 1, 7]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [34]:
np.add(ones_1,rand_array)

array([[ 2,  5, 10,  1,  5],
       [ 4,  7,  5,  9,  5],
       [ 5,  3,  9,  2,  8]])

In [39]:
ones_2 =np.ones((5,3),int)
ones_2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.dot(ones_2,rand_array)

array([[ 8, 12, 21,  9, 15],
       [ 8, 12, 21,  9, 15],
       [ 8, 12, 21,  9, 15],
       [ 8, 12, 21,  9, 15],
       [ 8, 12, 21,  9, 15]])

In [44]:
# Subtract the new array of ones from the other most recent array
np.subtract(ones_2,ones_1)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [45]:
ones_2**2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [46]:
np.square(rand_array)

array([[ 1, 16, 81,  0, 16],
       [ 9, 36, 16, 64, 16],
       [16,  4, 64,  1, 49]], dtype=int32)

In [47]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array)

4.333333333333333

In [49]:
# Find the maximum of the latest array using np.max()
np.max(rand_array)

9

In [50]:
np.min(rand_array)

0

In [51]:
np.std(rand_array)

2.6749870196985173

In [52]:
np.var(rand_array)

7.155555555555556

In [54]:
# Reshape the latest array to (3, 5, 1)
ones_2.reshape(3, 5, 1)


array([[[1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1]]])

## Viewing and selecting data

In [1]:
# you first view the header of the data frame to get some clue what the dataframe contains
car_sales.head()

NameError: name 'car_sales' is not defined