In [2]:
import numpy as np


In [4]:
oneDArray=np.array([1,2,3,4,5])
print(oneDArray)

[1 2 3 4 5]


In [6]:
# to chack the dimension we do (oneDArray,ndim)
print(oneDArray.ndim)

1


In [10]:
## 2D NUMPY ARRAY
twoDarray=np.array([[1,2,3],[4,5,6]])
print(twoDarray)


[[1 2 3]
 [4 5 6]]


In [11]:
print(twoDarray.ndim)

2


In [13]:
threeDArray=np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


## MATHEMATICS FOR DATA SCIENCE


.ZEROS()

to create a numpy arry filled with ,we can use .zeros()built in numy function .zeros() gives us a list prefilled with float zeros.to convert the list into int we us " astype() " 


In [7]:
zerroArray=np.zeros((10,3))
print(zerroArray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
zerroArray.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

.ONES()

TO creae a numpy array prefilled with ones we can use .ones() built in numpy .to convert them from float to int we usue. astype()

In [12]:
OnesArray=np.ones((5,3))
print(OnesArray)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
OnesArray.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

.full()

to create a numpy array prefilled with a specific number we can use .fill().first argument is the size of an array,while the seond is the number to befilled

In [15]:
fullArray=np.full((2,3),5)
print(fullArray)

[[5 5 5]
 [5 5 5]]


# Python pandas (Datfframe and series)

creating a dataframe using lists

we pass the list as an argument to the pandas DqtaFrame  
pandas assigns row labels 

In [16]:
import pandas as pd

mylist=[["Apple","red"],["Banana","yellow"],["Orange","Orange"]]

C:\Users\user\AppData\Local\Temp\ipykernel_8292\385881243.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [18]:
myDataframe=pd.DataFrame(mylist)
myDataframe

0       1
0   Apple     red
1  Banana  yellow
2  Orange  Orange

In [21]:
myDataframe=pd.DataFrame(mylist,columns=['Fruit','color'])
myDataframe

Fruit   color
0   Apple     red
1  Banana  yellow
2  Orange  Orange

#### create a data freame using a dictionary

> we can also pass a dictionary to the pandas .DataFrame()function to create a DataFrame

> each key of the array should have one or more values associated with it

> the keys f the dictinary become column

> pandas automatically assigns numerical row labels toeach row of the dataframe

 

In [23]:
mydictionary={'Fruit':['Apple','Banana','Orange'],'color':['red','yellow','Orange']}

In [25]:
mydataFrame=pd.DataFrame(mydictionary)
mydataFrame

Fruit   color
0   Apple     red
1  Banana  yellow
2  Orange  Orange

### Loading csv file


In [42]:
df=pd.read_csv(r"C:\Users\user\Desktop\POSITION PAPER\cereals.csv")
df

name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

Changing the index column

we can set one f the existinfas the new index column of the dataframe  using *.set_index()* function

In [38]:
df.set_index('name')


calories  protein  vitamins     rating
name                                                             
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
Basic 4                         130        3        25  37.038562
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813

In [29]:
df

name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

### pandas dataframe is immutable so we use INPLACE to make parmanent changes in our dataframe. we set inplace=TRUE

In [43]:
df.set_index('name',inplace=True)


#### Examinig dataframe:Head and Tail
head()-returns the first five rows but toget more rows we can pass the desired number as an argument o the head function

tail()-gives us the last five rowaof the dataframe,to get more we can pass the desired number as anargument of the tail unction


In [44]:
df.head()

calories  protein  vitamins     rating
name                                                             
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843

In [46]:
df.head(3)

calories  protein  vitamins     rating
name                                                     
100% Bran                70        4        25  68.402973
100% Natural Bran       120        3         0  33.983679
All-Bran                 70        4        25  59.425505

In [47]:
df.tail(7)

calories  protein  vitamins     rating
name                                                             
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
Basic 4                         130        3        25  37.038562
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813

In [48]:
df.describe()

calories    protein   vitamins     rating
count   10.000000  10.000000  10.000000  10.000000
mean    95.000000   2.900000  22.500000  49.205817
std     25.495098   0.875595   7.905694  20.315297
min     50.000000   2.000000   0.000000  29.509541
25%     75.000000   2.000000  25.000000  34.083970
50%    100.000000   3.000000  25.000000  43.079408
75%    110.000000   3.750000  25.000000  57.897582
max    130.000000   4.000000  25.000000  93.704912

## [] Operator for row slicing

In [50]:
df[::4]

calories  protein  vitamins     rating
name                                                  
100% Bran             70        4        25  68.402973
Almond Delight       110        2        25  34.384843
Bran Chex             90        2        25  49.120253

In [51]:
df[1:4]

calories  protein  vitamins     rating
name                                                             
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912